#!/usr/local/bin/node
// ^^ The tasks command file should have a shebang pointing to node
// shebang tells you what interpreter to use to run the file
// could also be #!/usr/bin/env node


// Tasks are persisted in a Postgres database
// The schema for the database exists in ./schema.sql
// Your package.json contains scripts to setup the database
// A separate test database exists for your tests
// All SQL functions are tested with mocha and chai

// The functions that execute the four command line commands
const { list, add, update } = require('./database/queries.js');

// assign task instructions to command and task
const command = process.argv[2];
// const task = process.argv.slice(3).join(' ');
const task = process.argv[3];

// log error if missing command
if (!command) {
  console.log('  Missing command - options are "add", "delete", "complete", and "list"');
  process.exit(1);
}

// check for existence of task - used in todoThing()
function taskExists() {
  if (!task) {
    console.log('  Missing task or task number');
    console.log('  - "add" should be followed by a task description');
    console.log('  - "delete" and "complete" should be followed by a task number');
    process.exit(1);
  }
}

function todoThing() {
  switch (command) {
    case 'list':
      list(console.log);
      break;
    case 'add':
      taskExists();
      add(task, console.log);
      break;
    case 'delete':
      taskExists();
      update('deleted', task, console.log);
      break;
    case 'complete':
      taskExists();
      update('completed', task, console.log);
      break;
    default:
      console.log('  Invalid command- options are "add", "delete", "complete", and "list"');
  }
}

todoThing();
